font:
  normal:
    family: FuraMono Nerd Font
    style: Regular
  bold:
    family: FuraMono Nerd Font
    style: Medium
  size: 14
  offset:
    y: 0

window:
  startup_mode: Fullscreen
  padding:
    x: 5
  title: Terminal

key_bindings:
  - { key: Back, mods: Alt, chars: "\u0008" }

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach -t base || tmux new -s base"

schemes:
  gruvbox_material_hard_dark: &gruvbox_material_hard_dark
    primary:
      background: '0x1d2021'
      foreground: '0xd4be98'
    normal:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
colors: *gruvbox_material_hard_dark

bell:
  duration: 0
